#!/bin/bash

# copy the backed up config file into the config directory
# else copy the autoconfig file into the config directory
if [ -f $OPENSHIFT_DATA_DIR/config.php ]
then
    cp $OPENSHIFT_DATA_DIR/config.php $OPENSHIFT_REPO_DIR/php/config
elif [ -f $OPENSHIFT_REPO_DIR/misc/autoconfig.php ]
then
    cp $OPENSHIFT_REPO_DIR/misc/autoconfig.php $OPENSHIFT_REPO_DIR/php/config
    php $OPENSHIFT_REPO_DIR/php/index.php # trigger the autoconfig
fi
